import type { Lesson } from "../lessonTypes";

export const BIOLOGY_ENZYMES: Lesson = {
  schema: 1,
  id: "biology.enzymes",
  version: 1,
  subject: "Biology",
  skillId: "enzymes",
  title: "Enzymes: mechanism, rate and experiments",
  minutes: 35,
  objectives: [
    "Explain how enzymes speed up reactions by lowering activation energy without being consumed.",
    "Relate an enzyme's 3D shape and active site to its specificity.",
    "Predict and explain the effects of temperature, pH, substrate concentration and inhibitors on rate.",
    "Design a fair enzyme experiment with controls, replicates and a measurable rate.",
    "Interpret enzyme rate data and justify conclusions from evidence.",
  ],
  prerequisiteReview: [
    { skillId: "biomolecules", text: "Most enzymes are proteins. A protein's amino-acid sequence folds into a specific 3D shape held by hydrogen bonds, ionic bonds and other interactions; heat and extreme pH can disrupt these." },
    { skillId: "experimental_design", text: "Independent variable: what you change. Dependent variable: what you measure. Controlled variables: kept the same. A control group shows what happens without the factor being tested." },
  ],
  concept: [
    { kind: "text", text: "Enzymes are biological catalysts. Almost all are proteins (a few are RNA molecules called ribozymes). They speed up reactions inside and outside cells that would otherwise be far too slow at body temperature." },
    { kind: "text", text: "Every reaction must pass through a high-energy transition state. An enzyme binds the substrate in its active site and stabilises that transition state, lowering the activation energy. More substrate molecules can then react per second. The enzyme is unchanged at the end and can be reused." },
    { kind: "callout", tone: "note", text: "Enzymes change how fast equilibrium is reached, not where it lies. They cannot make an energetically unfavourable reaction proceed on its own." },
    { kind: "definition", term: "Active site", text: "The region of the enzyme whose shape and chemical groups fit and bind a particular substrate." },
    { kind: "definition", term: "Induced fit", text: "Binding causes the active site to change shape slightly, gripping the substrate more tightly and straining the bonds that will break." },
    { kind: "definition", term: "Denaturation", text: "Loss of the enzyme's 3D shape (for example, from high temperature or extreme pH). The active site no longer fits the substrate, so activity is lost; this is often irreversible." },
    { kind: "table", caption: "Factors that affect rate", headers: ["Factor", "Effect", "Mechanism"], rows: [
      ["Temperature", "Rate rises to an optimum, then falls sharply", "More collisions and energy, until bonds holding the shape break"],
      ["pH", "Each enzyme has an optimum pH", "Charges on amino acids in the active site change; extremes denature"],
      ["Substrate conc.", "Rate rises then levels off", "At high concentration every active site is occupied (saturation)"],
      ["Competitive inhibitor", "Lowers rate; overcome by more substrate", "Competes for the active site"],
      ["Non-competitive inhibitor", "Lowers maximum rate; not overcome by substrate", "Binds elsewhere and changes the active site's shape"],
    ] },
  ],
  formal: [
    { kind: "text", text: "The catalytic cycle:" },
    { kind: "formula", text: "E + S ⇌ ES → E + P", note: "E enzyme, S substrate, ES enzyme–substrate complex, P product" },
    { kind: "text", text: "Rate is measured as amount of product formed (or substrate used) per unit time, ideally at the start of the reaction (initial rate) before substrate runs low. If you measure the time t for a fixed amount of change, rate ∝ 1/t." },
    { kind: "text", text: "Example: catalase, found in most aerobic cells, breaks down toxic hydrogen peroxide. The oxygen released can be collected and measured." },
    { kind: "chem", text: "2H₂O₂ → 2H₂O + O₂" },
    { kind: "formula", text: "Q₁₀ = rate at (T + 10 °C) / rate at T", note: "often about 2 below the optimum" },
  ],
  workedExamples: [
    {
      id: "we1",
      title: "Interpreting temperature data",
      problem: [
        { kind: "text", text: "Catalase from potato was mixed with H₂O₂ at different temperatures. Mean O₂ production (3 repeats):" },
        { kind: "table", headers: ["Temperature (°C)", "O₂ rate (mL/min)"], rows: [["10", "4"], ["20", "8"], ["30", "15"], ["40", "22"], ["50", "9"], ["60", "1"]] },
        { kind: "text", text: "Describe and explain the pattern, estimate the optimum and calculate Q₁₀ between 10 and 20 °C." },
      ],
      steps: [
        { text: "Describe: rate increases from 10 to 40 °C, then drops steeply to nearly zero by 60 °C." },
        { text: "Explain the rise: molecules move faster, so enzyme–substrate collisions are more frequent and more of them have enough energy to react." },
        { text: "Explain the fall: above about 40 °C, vibrations break bonds that hold the enzyme's shape. The active site deforms, fewer ES complexes form, and the enzyme denatures." },
        { text: "Estimate the optimum: the highest measured rate is at 40 °C, but the true optimum lies somewhere between 30 and 50 °C. Smaller temperature steps would narrow it." },
        { text: "Q₁₀ from 10 to 20 °C.", math: "Q₁₀ = 8 / 4 = 2" },
      ],
      answer: "Optimum near 40 °C (between 30 and 50 °C); Q₁₀ = 2.",
      check: "The steep fall is much faster than the gradual rise, which is typical of denaturation rather than slowing molecules.",
      verify: [{ expr: "8/4", equals: 2 }],
    },
    {
      id: "we2",
      title: "Designing a fair pH experiment",
      problem: [{ kind: "text", text: "Design an experiment to find the effect of pH on the rate at which amylase breaks down starch." }],
      steps: [
        { text: "Independent variable: pH, set with buffers at pH 4, 5, 6, 7 and 8." },
        { text: "Dependent variable: time for starch to disappear, tested every 10 s by putting a drop of the mixture into iodine (blue-black → stays orange-brown when starch is gone). Rate = 1/time." },
        { text: "Controlled variables: temperature (water bath), volume and concentration of amylase and starch, and the time between samples." },
        { text: "Control: boiled (denatured) amylase at each pH. If starch still disappears, something other than the enzyme is responsible." },
        { text: "Replicates: three repeats per pH; calculate a mean and look at the spread to judge reliability." },
        { text: "Processing: if starch disappears in 50 s, rate = 1000/50 = 20 (units of 1000/s) — scaling makes small numbers easier to compare.", math: "rate = 1000 / t = 1000 / 50 = 20" },
      ],
      answer: "A buffered series with controlled temperature and concentrations, a boiled-enzyme control, three repeats, and rate calculated as 1/time.",
      verify: [{ expr: "1000/50", equals: 20 }],
    },
  ],
  misconceptions: [
    { claim: "High temperatures kill enzymes.", correction: "Enzymes are molecules, not living things. They are denatured: their shape changes and the active site no longer fits." },
    { claim: "Enzymes are used up in reactions.", correction: "They are regenerated at the end of each cycle and can catalyse many reactions." },
    { claim: "Low temperatures denature enzymes.", correction: "Cold mainly slows molecular motion. Activity usually returns when warmed, because the shape is intact." },
    { claim: "All enzymes work best at 37 °C and pH 7.", correction: "Optima match the enzyme's environment: pepsin works best around pH 2 in the stomach; DNA polymerase from heat-loving bacteria works near 72 °C." },
  ],
  guided: [
    {
      id: "g1", type: "mcq", difficulty: 2, focus: "conceptual",
      prompt: [{ kind: "text", text: "Rate has stopped increasing even though more substrate is added. What happens if you add even more substrate?" }],
      options: ["Rate rises sharply", "Rate stays about the same", "The enzyme denatures"], answer: 1,
      hints: ["Why did the rate stop increasing?", "Think about how many active sites are free."],
      explanation: "The enzyme is saturated: every active site is busy. Only more enzyme (or a higher temperature below the optimum) would raise the rate.",
    },
    {
      id: "g2", type: "numeric", difficulty: 1, focus: "procedural", unit: "mL/s",
      prompt: [{ kind: "text", text: "24 mL of oxygen was collected in the first 60 s. What is the mean rate of oxygen production?" }],
      hints: ["Rate = amount ÷ time.", "24 ÷ 60."],
      answer: 0.4, tolerance: 0.001, verify: { expr: "24/60", equals: 0.4 },
      explanation: "24 mL ÷ 60 s = 0.40 mL/s.",
    },
    {
      id: "g3", type: "mcq", difficulty: 2, focus: "conceptual", gapSkill: "experimental_design",
      prompt: [{ kind: "text", text: "Why include a tube with boiled enzyme in an enzyme experiment?" }],
      options: ["To speed up the reaction", "To show that any change is caused by active enzyme", "To keep temperature constant", "To provide more substrate"],
      answer: 1,
      hints: ["What does boiling do to the enzyme?", "If the change still happens without active enzyme, what would that mean?"],
      explanation: "Boiling denatures the enzyme. If no reaction occurs in that tube, the change in the others must be due to the active enzyme.",
    },
  ],
  exercises: [
    { id: "e1", type: "mcq", difficulty: 1, focus: "conceptual", prompt: [{ kind: "text", text: "How does an enzyme increase reaction rate?" }], options: ["It raises the temperature", "It lowers the activation energy", "It adds energy to the products", "It shifts equilibrium toward products"], answer: 1, hints: ["Think of the energy barrier."], explanation: "Enzymes stabilise the transition state, lowering activation energy. They do not change equilibrium position." },
    { id: "e2", type: "mcq", difficulty: 2, focus: "application", prompt: [{ kind: "text", text: "Pepsin has an optimum near pH 2. What happens to its activity when it reaches the small intestine at about pH 7–8?" }], options: ["It increases", "It falls sharply", "It is unchanged", "It doubles every pH unit"], answer: 1, hints: ["Charges in the active site depend on pH."], explanation: "Away from its optimum, pepsin's active-site charges and shape change, so activity falls sharply." },
    { id: "e3", type: "numeric", difficulty: 2, focus: "procedural", prompt: [{ kind: "text", text: "An enzyme reaction has a rate of 12 units at 25 °C and 27 units at 35 °C. Calculate Q₁₀." }], hints: ["Q₁₀ = higher rate ÷ lower rate for a 10 °C rise."], answer: 2.25, tolerance: 0.001, verify: { expr: "27/12", equals: 2.25 }, explanation: "Q₁₀ = 27 / 12 = 2.25." },
    { id: "e4", type: "mcq", difficulty: 2, focus: "conceptual", prompt: [{ kind: "text", text: "Adding a large excess of substrate restores the maximum rate in the presence of an inhibitor. What kind of inhibitor is it most likely to be?" }], options: ["Competitive", "Non-competitive", "A denaturing agent"], answer: 0, hints: ["Which kind competes for the same site?"], explanation: "Competitive inhibitors occupy the active site; enough substrate out-competes them. Non-competitive inhibitors change the site's shape regardless." },
    { id: "e5", type: "order", difficulty: 1, focus: "conceptual", prompt: [{ kind: "text", text: "Put the catalytic cycle in order." }], items: ["Substrate binds to the active site", "Enzyme–substrate complex forms; induced fit strains bonds", "Substrate is converted to products", "Products are released; enzyme is unchanged"], hints: ["Binding must come first."], explanation: "Binding → ES complex → reaction → release, and the enzyme is free to bind again." },
    { id: "e6", type: "match", difficulty: 1, focus: "conceptual", prompt: [{ kind: "text", text: "Match each term to its meaning." }], pairs: [["Active site", "Region that binds the substrate"], ["Denaturation", "Permanent loss of 3D shape"], ["Saturation", "All active sites occupied"], ["Cofactor", "Non-protein helper needed for activity"]], hints: ["Start with the one you are surest about."], explanation: "These four ideas explain most enzyme rate graphs." },
    {
      id: "e7", type: "mcq", difficulty: 3, focus: "application", gapSkill: "experimental_design",
      prompt: [{ kind: "text", text: "A student tests catalase at different H₂O₂ concentrations. Tubes were set up in the morning (room 18 °C) and afternoon (room 26 °C). What is the main flaw?" }],
      options: ["Too many concentrations", "Temperature was not controlled, so it is confounded with concentration", "Catalase does not act on H₂O₂", "Oxygen cannot be measured"], answer: 1,
      hints: ["What else changed besides the independent variable?"],
      explanation: "Temperature also affects rate. Without a water bath, differences may come from temperature, not concentration.",
    },
    { id: "e8", type: "short", difficulty: 2, focus: "conceptual", prompt: [{ kind: "text", text: "Explain why the rate of an enzyme reaction falls above the optimum temperature." }], hints: ["Mention shape and the active site."], modelAnswer: "Above the optimum, increased vibration breaks the bonds that hold the enzyme's tertiary structure. The active site changes shape, so the substrate no longer fits and fewer enzyme–substrate complexes form. The enzyme is denatured, so the rate falls.", rubric: ["Bonds holding structure break", "Active site changes shape", "Fewer ES complexes / substrate no longer fits", "Uses the word denatured correctly"], explanation: "A complete answer links temperature → structure → active site → rate." },
  ],
  application: {
    title: "Making lactose-free milk",
    scenario: [
      { kind: "text", text: "Lactase breaks lactose into glucose and galactose. A dairy compares two amounts of lactase in the same volume of milk at 30 °C. Glucose concentration (mmol/L):" },
      { kind: "table", headers: ["Time (min)", "1 unit lactase", "2 units lactase"], rows: [["0", "0", "0"], ["5", "10", "20"], ["10", "19", "35"], ["20", "33", "45"], ["40", "45", "46"]] },
    ],
    questions: [
      { id: "ap1", type: "numeric", difficulty: 2, focus: "application", unit: "mmol/L per min", prompt: [{ kind: "text", text: "Calculate the initial rate (first 5 minutes) with 2 units of lactase." }], hints: ["Change in glucose ÷ time.", "20 ÷ 5."], answer: 4, tolerance: 0.001, verify: { expr: "20/5", equals: 4 }, explanation: "20 mmol/L ÷ 5 min = 4 mmol/L per min, double the 2 mmol/L per min with 1 unit." },
      { id: "ap2", type: "mcq", difficulty: 3, focus: "application", prompt: [{ kind: "text", text: "Why do both curves level off near the same glucose concentration?" }], options: ["The enzyme is denatured after 20 minutes", "The lactose is used up; enzyme amount changes speed, not final amount", "Glucose inhibits all enzymes", "30 °C is above lactase's optimum"], answer: 1, hints: ["What runs out in a closed container of milk?"], explanation: "The final amount of product is set by the lactose available. More enzyme just reaches that point faster." },
      { id: "ap3", type: "short", difficulty: 2, focus: "application", prompt: [{ kind: "text", text: "The dairy wants to save money. Use the data to recommend an amount of enzyme and processing time." }], hints: ["Look at when each curve gets close to its maximum."], modelAnswer: "With 2 units the milk is nearly complete by 20 min (45 of about 46); with 1 unit it takes about 40 min. If processing time is cheap, 1 unit for 40 min halves enzyme cost; if throughput matters, 2 units for 20 min. Repeats would be needed to confirm.", rubric: ["Uses specific values from the table", "Identifies the trade-off between time and enzyme", "Makes a justified recommendation"], explanation: "Evidence-based recommendations quote the data and state their assumptions." },
    ],
  },
  assessment: [
    { id: "a1", type: "mcq", difficulty: 1, focus: "conceptual", prompt: [{ kind: "text", text: "Which statement about enzymes is correct?" }], options: ["They are consumed in the reaction", "They change the equilibrium position", "They lower activation energy and are reused", "They work equally well at all temperatures"], answer: 2, hints: [], explanation: "Enzymes lower activation energy, are regenerated, and do not change equilibrium." },
    { id: "a2", type: "mcq", difficulty: 2, focus: "conceptual", prompt: [{ kind: "text", text: "Why does an enzyme usually act on only one substrate?" }], options: ["Its active site has a complementary shape and chemistry to that substrate", "It is only made when that substrate is present", "Other substrates are too large to collide", "Enzymes only exist inside one organelle"], answer: 0, hints: [], explanation: "Specificity comes from the complementary shape and chemical groups of the active site." },
    { id: "a3", type: "numeric", difficulty: 2, focus: "procedural", prompt: [{ kind: "text", text: "Starch disappeared after 40 s. Calculate the rate as 1000/time." }], hints: [], answer: 25, tolerance: 0.001, verify: { expr: "1000/40", equals: 25 }, explanation: "1000 / 40 = 25 (arbitrary units of 1000/s)." },
    { id: "a4", type: "mcq", difficulty: 2, focus: "application", gapSkill: "experimental_design", prompt: [{ kind: "text", text: "Which is the best control when testing whether a leaf extract contains catalase?" }], options: ["The same extract after boiling, added to H₂O₂", "More H₂O₂", "A different leaf", "Running the test at a higher temperature"], answer: 0, hints: [], explanation: "Boiled extract keeps everything the same except active enzyme." },
    { id: "a5", type: "mcq", difficulty: 3, focus: "conceptual", prompt: [{ kind: "text", text: "An inhibitor lowers the maximum rate, and adding more substrate does not restore it. What is the best explanation?" }], options: ["It competes for the active site", "It binds elsewhere and changes the active site's shape", "It adds more substrate", "It increases activation energy of the uncatalysed reaction"], answer: 1, hints: [], explanation: "This describes non-competitive inhibition: binding at another site alters the active site, so substrate cannot out-compete it." },
  ],
  summary: {
    points: [
      "Enzymes are reusable catalysts that lower activation energy; they do not change equilibrium.",
      "Specificity comes from the active site's complementary shape; induced fit tightens binding.",
      "Rate rises with temperature to an optimum, then falls as the enzyme denatures; pH has an optimum too.",
      "Substrate saturation limits rate; competitive inhibition is overcome by substrate, non-competitive is not.",
      "Fair tests control variables, include a boiled-enzyme control, repeat, and measure initial rate.",
    ],
    formulas: ["E + S ⇌ ES → E + P", "rate ∝ 1/time", "Q₁₀ = rate(T+10)/rate(T)"],
  },
};
