import type { Lesson } from "../lessonTypes";

export const MATH_LINEAR_EQUATIONS: Lesson = {
  schema: 1,
  id: "math.linear_equations",
  version: 1,
  subject: "Math",
  skillId: "linear_equations",
  title: "Solving linear equations",
  minutes: 35,
  objectives: [
    "Explain why doing the same operation to both sides keeps the solutions of an equation unchanged.",
    "Solve linear equations with brackets, variables on both sides, fractions and decimals.",
    "Recognise equations with no solution and equations true for every number.",
    "Check a solution by substituting it into the original equation.",
    "Translate a word problem into a linear equation and interpret the answer with units.",
  ],
  prerequisiteReview: [
    { skillId: "algebraic_expressions", text: "Expanding brackets: 3(x − 4) = 3x − 12. Every term inside is multiplied. Collecting like terms: 3x − 7x = −4x." },
    { skillId: "fraction_operations", text: "To remove fractions, multiply by a common denominator: 12 · (x/3) = 4x and 12 · (x/4) = 3x." },
  ],
  concept: [
    { kind: "text", text: "An equation says two expressions have the same value. Solving it means finding every value of the unknown that makes the statement true. That set of values is the solution set." },
    { kind: "text", text: "Think of a balance. If you add, subtract, multiply or divide both sides by the same number (never multiply or divide by zero), the balance stays level, so the solution set does not change. Each step produces a simpler equivalent equation until the unknown stands alone." },
    { kind: "definition", term: "Linear equation (in one unknown)", text: "An equation that can be rearranged to ax + b = 0 with a ≠ 0. The unknown appears only to the first power and is never inside a denominator or root." },
    { kind: "list", ordered: true, items: [
      "Clear fractions by multiplying both sides by the least common denominator.",
      "Expand brackets.",
      "Collect the unknown on one side and constants on the other.",
      "Divide by the coefficient of the unknown.",
      "Substitute back into the original equation to check.",
    ] },
    { kind: "callout", tone: "note", text: "\"Moving a term to the other side and changing its sign\" is shorthand for subtracting (or adding) that term on both sides. Use the full operation when unsure." },
  ],
  formal: [
    { kind: "text", text: "General solution. Start from ax + b = c with a ≠ 0." },
    { kind: "formula", text: "ax + b = c", note: "given" },
    { kind: "formula", text: "ax = c − b", note: "subtract b from both sides" },
    { kind: "formula", text: "x = (c − b) / a", note: "divide both sides by a (allowed because a ≠ 0)" },
    { kind: "text", text: "Special cases arise when the x-terms cancel. If you reach 0 = k with k ≠ 0, no number works: there is no solution. If you reach 0 = 0, every real number works: the equation is an identity." },
  ],
  workedExamples: [
    {
      id: "we1",
      title: "Brackets and unknowns on both sides",
      problem: [{ kind: "formula", text: "3(x − 4) + 5 = 2x + 7" }],
      steps: [
        { text: "Expand the bracket. The 3 multiplies both x and −4.", math: "3x − 12 + 5 = 2x + 7" },
        { text: "Combine constants on the left.", math: "3x − 7 = 2x + 7" },
        { text: "Subtract 2x from both sides.", math: "x − 7 = 7" },
        { text: "Add 7 to both sides.", math: "x = 14" },
      ],
      answer: "x = 14",
      check: "Left: 3(14 − 4) + 5 = 35. Right: 2(14) + 7 = 35. Both sides agree.",
      verify: [{ expr: "3*(14-4)+5", equals: 35 }, { expr: "2*14+7", equals: 35 }],
    },
    {
      id: "we2",
      title: "Clearing fractions",
      problem: [{ kind: "formula", text: "(x + 2)/3 − (x − 1)/4 = 2" }],
      steps: [
        { text: "The least common denominator of 3 and 4 is 12. Multiply every term on both sides by 12.", math: "4(x + 2) − 3(x − 1) = 24" },
        { text: "Expand. Note −3 · (−1) = +3.", math: "4x + 8 − 3x + 3 = 24" },
        { text: "Collect like terms.", math: "x + 11 = 24" },
        { text: "Subtract 11 from both sides.", math: "x = 13" },
      ],
      answer: "x = 13",
      check: "(13 + 2)/3 − (13 − 1)/4 = 5 − 3 = 2.",
      verify: [{ expr: "(13+2)/3-(13-1)/4", equals: 2 }],
    },
    {
      id: "we3",
      title: "From a word problem to an equation",
      problem: [{ kind: "text", text: "A taxi charges a fixed 2.50 plus 1.20 per kilometre. A ride cost 14.50. How far was it?" }],
      given: ["Fixed fee = 2.50", "Rate = 1.20 per km", "Total = 14.50", "Unknown: distance d in km"],
      steps: [
        { text: "Write total cost as fixed fee plus rate times distance.", math: "2.50 + 1.20d = 14.50" },
        { text: "Subtract 2.50 from both sides.", math: "1.20d = 12.00" },
        { text: "Divide both sides by 1.20.", math: "d = 12.00 / 1.20 = 10" },
      ],
      answer: "The ride was 10 km.",
      check: "2.50 + 1.20 × 10 = 14.50.",
      verify: [{ expr: "(14.5-2.5)/1.2", equals: 10 }],
    },
  ],
  misconceptions: [
    { claim: "3(x − 4) = 3x − 4.", correction: "The factor multiplies every term in the bracket: 3(x − 4) = 3x − 12." },
    { claim: "When clearing fractions, only the fraction terms need multiplying.", correction: "Every term on both sides is multiplied, including whole numbers. Otherwise the balance is broken." },
    { claim: "If the x-terms cancel and you get 0 = 5, then x = 0.", correction: "0 = 5 is false for every x, so the equation has no solution. x = 0 would give 0 = 5, which is not true." },
    { claim: "Moving a term across the equals sign is a special rule.", correction: "It is just adding or subtracting the same term on both sides; understanding that prevents sign errors." },
  ],
  guided: [
    {
      id: "g1", type: "numeric", difficulty: 1, focus: "procedural",
      prompt: [{ kind: "text", text: "Solve for x." }, { kind: "formula", text: "5x − 7 = 18" }],
      hints: ["Undo the subtraction first: add 7 to both sides.", "You should have 5x = 25.", "Divide both sides by 5."],
      answer: 5, tolerance: 0, verify: { expr: "(18+7)/5", equals: 5 },
      explanation: "5x − 7 = 18 → 5x = 25 → x = 5. Check: 5(5) − 7 = 18.",
    },
    {
      id: "g2", type: "numeric", difficulty: 2, focus: "procedural", gapSkill: "algebraic_expressions",
      prompt: [{ kind: "text", text: "Solve for x." }, { kind: "formula", text: "2(x + 3) = x − 4" }],
      hints: ["Expand the bracket: 2x + 6.", "Subtract x from both sides: x + 6 = −4.", "Subtract 6 from both sides."],
      answer: -10, tolerance: 0,
      explanation: "2x + 6 = x − 4 → x + 6 = −4 → x = −10. Check: 2(−7) = −14 and −10 − 4 = −14.",
    },
    {
      id: "g3", type: "order", difficulty: 1, focus: "conceptual",
      prompt: [{ kind: "text", text: "Put the steps for solving x/2 + 3 = 7 in order." }],
      items: ["Subtract 3 from both sides: x/2 = 4", "Multiply both sides by 2: x = 8", "Check: 8/2 + 3 = 7"],
      hints: ["Undo the operation applied last to x first.", "Division by 2 happened before adding 3, so undo the + 3 first."],
      explanation: "Undo operations in reverse order: remove + 3, then the division by 2, then check.",
    },
  ],
  exercises: [
    { id: "e1", type: "numeric", difficulty: 1, focus: "procedural", prompt: [{ kind: "formula", text: "4x + 9 = 1" }], hints: ["Subtract 9 from both sides."], answer: -2, tolerance: 0, verify: { expr: "(1-9)/4", equals: -2 }, explanation: "4x = −8, so x = −2." },
    { id: "e2", type: "numeric", difficulty: 2, focus: "procedural", prompt: [{ kind: "formula", text: "7 − 2x = 3x − 8" }], hints: ["Add 2x and add 8 to both sides."], answer: 3, tolerance: 0, verify: { expr: "(7+8)/5", equals: 3 }, explanation: "15 = 5x, so x = 3. Check: 7 − 6 = 1 and 9 − 8 = 1." },
    { id: "e3", type: "numeric", difficulty: 2, focus: "procedural", gapSkill: "algebraic_expressions", prompt: [{ kind: "formula", text: "3(2x − 1) − 2(x + 4) = 9" }], hints: ["Expand both brackets carefully: −2 multiplies +4 too."], answer: 5, tolerance: 0, verify: { expr: "(9+3+8)/4", equals: 5 }, explanation: "6x − 3 − 2x − 8 = 9 → 4x − 11 = 9 → 4x = 20 → x = 5." },
    { id: "e4", type: "numeric", difficulty: 2, focus: "procedural", gapSkill: "fraction_operations", prompt: [{ kind: "formula", text: "x/3 + x/6 = 5" }], hints: ["Multiply every term by 6."], answer: 10, tolerance: 0, verify: { expr: "5*6/3", equals: 10 }, explanation: "2x + x = 30 → 3x = 30 → x = 10." },
    { id: "e5", type: "numeric", difficulty: 2, focus: "procedural", prompt: [{ kind: "formula", text: "0.4x + 1.2 = 0.1x + 3" }], hints: ["Multiplying by 10 removes the decimals."], answer: 6, tolerance: 0, verify: { expr: "(3-1.2)/0.3", equals: 6 }, explanation: "0.3x = 1.8, so x = 6. Or ×10: 4x + 12 = x + 30 → 3x = 18." },
    {
      id: "e6", type: "mcq", difficulty: 2, focus: "conceptual",
      prompt: [{ kind: "text", text: "What is the solution set of 2(x + 1) = 2x + 5?" }],
      options: ["x = 0", "No solution", "Every real number", "x = 3/2"], answer: 1,
      optionFeedback: ["Substitute 0: 2 ≠ 5.", null, "That happens only when you reach 0 = 0.", "Substitute 1.5: 5 ≠ 8."],
      hints: ["Expand the left side and compare."], explanation: "2x + 2 = 2x + 5 gives 2 = 5 after subtracting 2x. False for every x, so there is no solution.",
    },
    {
      id: "e7", type: "mcq", difficulty: 1, focus: "conceptual",
      prompt: [{ kind: "text", text: "Which operation on both sides can change the solution set of an equation?" }],
      options: ["Adding 7", "Dividing by 3", "Multiplying by 0", "Subtracting x"], answer: 2,
      hints: ["Which operation cannot be undone?"], explanation: "Multiplying by 0 turns any equation into 0 = 0 and cannot be reversed, so solutions are lost or gained.",
    },
  ],
  application: {
    title: "Choosing a phone plan",
    scenario: [
      { kind: "text", text: "Plan A costs 15 per month plus 0.05 per minute. Plan B costs 5 per month plus 0.09 per minute. Let m be minutes used in a month." },
      { kind: "formula", text: "A = 15 + 0.05m      B = 5 + 0.09m" },
    ],
    questions: [
      { id: "ap1", type: "numeric", difficulty: 2, focus: "application", prompt: [{ kind: "text", text: "For how many minutes do the plans cost the same?" }], hints: ["Set A = B.", "15 + 0.05m = 5 + 0.09m → 10 = 0.04m."], answer: 250, tolerance: 0, unit: "min", verify: { expr: "(15-5)/(0.09-0.05)", equals: 250 }, explanation: "10 = 0.04m, so m = 250 minutes. Both cost 27.50." },
      { id: "ap2", type: "mcq", difficulty: 2, focus: "application", prompt: [{ kind: "text", text: "A student uses about 300 minutes a month. Which plan is cheaper?" }], options: ["Plan A", "Plan B", "They cost the same"], answer: 0, hints: ["Substitute m = 300 into both."], explanation: "A = 15 + 15 = 30; B = 5 + 27 = 32. Above 250 minutes, Plan A's lower rate wins." },
      { id: "ap3", type: "short", difficulty: 2, focus: "application", prompt: [{ kind: "text", text: "Explain to a friend how to decide which plan to pick without testing every number of minutes." }], hints: ["Use the break-even point."], modelAnswer: "Find the break-even point by setting the costs equal: 250 minutes. Below that, the plan with the lower fixed fee (B) is cheaper; above it, the plan with the lower per-minute rate (A) is cheaper. Compare your typical usage to 250.", rubric: ["Sets the two costs equal", "States the break-even of 250 minutes", "Says which plan wins on each side"], explanation: "The break-even point splits the decision into two regions." },
    ],
  },
  assessment: [
    { id: "a1", type: "numeric", difficulty: 1, focus: "procedural", prompt: [{ kind: "formula", text: "6x − 5 = 2x + 11" }], hints: [], answer: 4, tolerance: 0, verify: { expr: "(11+5)/4", equals: 4 }, explanation: "4x = 16, so x = 4. Check: 19 = 19." },
    { id: "a2", type: "numeric", difficulty: 3, focus: "procedural", gapSkill: "fraction_operations", prompt: [{ kind: "formula", text: "(2x − 1)/5 = (x + 4)/3" }], hints: [], answer: 23, tolerance: 0, verify: { expr: "(20+3)/(6-5)", equals: 23 }, explanation: "Multiply by 15: 3(2x − 1) = 5(x + 4) → 6x − 3 = 5x + 20 → x = 23. Check: 45/5 = 9 and 27/3 = 9." },
    { id: "a3", type: "mcq", difficulty: 2, focus: "conceptual", prompt: [{ kind: "formula", text: "3x + 2 = 3(x + 1) − 1" }, { kind: "text", text: "How many solutions does this equation have?" }], options: ["Exactly one", "None", "Infinitely many"], answer: 2, hints: [], explanation: "The right side simplifies to 3x + 2, giving 0 = 0. Every real number is a solution." },
    {
      id: "a4", type: "mcq", difficulty: 2, focus: "conceptual", gapSkill: "algebraic_expressions",
      prompt: [{ kind: "text", text: "A student solves 2(x − 3) = 10 as: Step 1: 2x − 3 = 10. Step 2: 2x = 13. Step 3: x = 6.5. Where is the first error?" }],
      options: ["Step 1", "Step 2", "Step 3", "There is no error"], answer: 0, hints: [],
      explanation: "2(x − 3) = 2x − 6, not 2x − 3. The correct solution is 2x = 16, x = 8.",
    },
    { id: "a5", type: "numeric", difficulty: 2, focus: "application", prompt: [{ kind: "text", text: "A rectangle's length is 5 cm more than its width and its perimeter is 46 cm. Find the width." }], hints: [], answer: 9, tolerance: 0, unit: "cm", verify: { expr: "(46/2-5)/2", equals: 9 }, explanation: "2(w + w + 5) = 46 → 4w + 10 = 46 → w = 9 cm. Length 14 cm; 2(9 + 14) = 46." },
  ],
  summary: {
    points: [
      "Doing the same non-zero operation to both sides keeps the solutions unchanged.",
      "Clear fractions, expand, collect, divide, then check by substitution.",
      "0 = k (k ≠ 0) means no solution; 0 = 0 means every number is a solution.",
      "In word problems, define the unknown with its unit before writing the equation.",
    ],
    formulas: ["ax + b = c  ⇒  x = (c − b)/a,  a ≠ 0"],
  },
};
