import type { Lesson } from "../lessonTypes";

export const PHYSICS_ELECTRIC_CIRCUITS: Lesson = {
  schema: 1,
  id: "physics.electric_circuits",
  version: 1,
  subject: "Physics",
  skillId: "electric_circuits",
  title: "Current, voltage, resistance and simple circuits",
  minutes: 40,
  objectives: [
    "Define current, potential difference and resistance with their SI units.",
    "Apply Ohm's law V = IR to ohmic resistors.",
    "Calculate total resistance, currents and voltages in series and parallel circuits.",
    "Calculate electrical power and energy, and convert joules to kilowatt-hours.",
    "Explain circuit behaviour using conservation of charge and energy.",
  ],
  prerequisiteReview: [
    { skillId: "units_measurement", text: "SI prefixes: 1 mA = 10⁻³ A, 1 kΩ = 10³ Ω, 1 kW = 10³ W. 1 min = 60 s, 1 h = 3600 s. Convert to base units before calculating." },
  ],
  concept: [
    { kind: "text", text: "A circuit is a closed loop through which charge flows. A battery does not create charge; it gives each coulomb of charge energy. Components such as resistors and lamps transfer that energy to heat and light. The charge itself is not used up: the same current flows back to the battery." },
    { kind: "definition", term: "Current I (ampere, A)", text: "Rate of flow of charge: I = Q/t. 1 A = 1 coulomb per second." },
    { kind: "definition", term: "Potential difference V (volt, V)", text: "Energy transferred per unit charge between two points: V = E/Q. 1 V = 1 joule per coulomb." },
    { kind: "definition", term: "Resistance R (ohm, Ω)", text: "How much potential difference is needed per ampere of current: R = V/I. 1 Ω = 1 V/A." },
    { kind: "text", text: "For an ohmic conductor at constant temperature, current is proportional to potential difference, so R is constant. This is Ohm's law. Filament lamps and diodes are not ohmic: their resistance changes with current." },
    { kind: "table", caption: "Series vs parallel", headers: ["", "Series", "Parallel"], rows: [
      ["Current", "Same through every component", "Splits; branch currents add to the total"],
      ["Potential difference", "Shared; adds to supply voltage", "Same across every branch"],
      ["Total resistance", "R = R₁ + R₂ + …", "1/R = 1/R₁ + 1/R₂ + …"],
    ] },
  ],
  formal: [
    { kind: "text", text: "Series rule from energy conservation: each coulomb loses V₁ in R₁ and V₂ in R₂, so V = V₁ + V₂. The same current I flows through both, so IR = IR₁ + IR₂, giving:" },
    { kind: "formula", text: "R_series = R₁ + R₂" },
    { kind: "text", text: "Parallel rule from charge conservation: the total current splits, I = I₁ + I₂, and each branch has the same V. Dividing by V:" },
    { kind: "formula", text: "I/V = I₁/V + I₂/V  ⇒  1/R_parallel = 1/R₁ + 1/R₂" },
    { kind: "text", text: "Power is energy per second. Since V is energy per coulomb and I is coulombs per second:" },
    { kind: "formula", text: "P = IV = I²R = V²/R", note: "watts, W = J/s" },
    { kind: "formula", text: "E = Pt", note: "J if P in W and t in s; kWh if P in kW and t in h. 1 kWh = 3.6 × 10⁶ J" },
    { kind: "callout", tone: "assumption", text: "We treat wires as having zero resistance and batteries as ideal (no internal resistance) unless stated." },
  ],
  workedExamples: [
    {
      id: "we1",
      title: "Two resistors in series",
      problem: [{ kind: "text", text: "A 12 V battery is connected to a 4.0 Ω and a 2.0 Ω resistor in series. Find the current, the voltage across each resistor and the total power." }],
      given: ["V = 12 V", "R₁ = 4.0 Ω", "R₂ = 2.0 Ω"],
      steps: [
        { text: "Total resistance in series.", math: "R = 4.0 + 2.0 = 6.0 Ω" },
        { text: "Current from Ohm's law.", math: "I = V/R = 12 / 6.0 = 2.0 A" },
        { text: "Voltage across each resistor (same current through both).", math: "V₁ = 2.0 × 4.0 = 8.0 V,  V₂ = 2.0 × 2.0 = 4.0 V" },
        { text: "Total power.", math: "P = IV = 2.0 × 12 = 24 W" },
      ],
      answer: "I = 2.0 A; V₁ = 8.0 V, V₂ = 4.0 V; P = 24 W.",
      check: "8.0 V + 4.0 V = 12 V, the supply voltage, as energy conservation requires.",
      verify: [{ expr: "12/(4+2)", equals: 2 }, { expr: "2*4+2*2", equals: 12 }, { expr: "2*12", equals: 24 }],
    },
    {
      id: "we2",
      title: "Two resistors in parallel",
      problem: [{ kind: "text", text: "A 6.0 Ω and a 3.0 Ω resistor are connected in parallel to a 9.0 V supply. Find the total resistance, the total current and each branch current." }],
      given: ["V = 9.0 V", "R₁ = 6.0 Ω", "R₂ = 3.0 Ω"],
      steps: [
        { text: "Parallel combination.", math: "1/R = 1/6.0 + 1/3.0 = 1/6 + 2/6 = 3/6  ⇒  R = 2.0 Ω" },
        { text: "Total current.", math: "I = 9.0 / 2.0 = 4.5 A" },
        { text: "Each branch has the full 9.0 V.", math: "I₁ = 9.0/6.0 = 1.5 A,  I₂ = 9.0/3.0 = 3.0 A" },
      ],
      answer: "R = 2.0 Ω, I = 4.5 A, I₁ = 1.5 A, I₂ = 3.0 A.",
      check: "1.5 + 3.0 = 4.5 A. Also, the combined resistance is smaller than either branch, as expected for parallel.",
      verify: [{ expr: "1/(1/6+1/3)", equals: 2 }, { expr: "9/6+9/3", equals: 4.5 }],
    },
  ],
  misconceptions: [
    { claim: "Current gets used up by each lamp, so less returns to the battery.", correction: "Charge is conserved. The same current leaves and returns; it is energy that is transferred in the components." },
    { claim: "A battery always supplies the same current.", correction: "A battery provides a (nearly) fixed potential difference. The current depends on the resistance of the circuit." },
    { claim: "Adding another resistor in parallel increases total resistance.", correction: "It adds another path for charge, so total resistance decreases and total current increases." },
    { claim: "Voltage flows through a circuit.", correction: "Current flows through components; potential difference is measured across them, between two points." },
  ],
  guided: [
    {
      id: "g1", type: "numeric", difficulty: 1, focus: "procedural", unit: "A",
      prompt: [{ kind: "text", text: "A heater of resistance 46 Ω is connected to a 230 V supply. What current flows?" }],
      hints: ["Which equation links V, I and R?", "Rearrange V = IR for I.", "I = 230 / 46."],
      answer: 5, tolerance: 0.001, verify: { expr: "230/46", equals: 5 },
      explanation: "I = V/R = 230 V / 46 Ω = 5.0 A.",
    },
    {
      id: "g2", type: "numeric", difficulty: 2, focus: "procedural", unit: "V",
      prompt: [{ kind: "text", text: "A 10 Ω and a 15 Ω resistor are in series and carry 0.40 A. What is the supply voltage?" }],
      hints: ["Series resistances add.", "R = 25 Ω.", "V = IR = 0.40 × 25."],
      answer: 10, tolerance: 0.001, verify: { expr: "0.4*(10+15)", equals: 10 },
      explanation: "R = 25 Ω, V = 0.40 A × 25 Ω = 10 V.",
    },
    {
      id: "g3", type: "numeric", difficulty: 2, focus: "procedural", unit: "Ω",
      prompt: [{ kind: "text", text: "Two 12 Ω resistors are connected in parallel. What is their combined resistance?" }],
      hints: ["Use 1/R = 1/R₁ + 1/R₂.", "1/12 + 1/12 = 2/12.", "Remember to invert at the end."],
      answer: 6, tolerance: 0.001, verify: { expr: "1/(1/12+1/12)", equals: 6 },
      explanation: "1/R = 2/12 = 1/6, so R = 6.0 Ω. Two equal resistors in parallel give half of one.",
    },
  ],
  exercises: [
    { id: "e1", type: "numeric", difficulty: 1, focus: "procedural", gapSkill: "units_measurement", unit: "C", prompt: [{ kind: "text", text: "A current of 0.50 A flows for 2.0 minutes. How much charge passes?" }], hints: ["Convert minutes to seconds first."], answer: 60, tolerance: 0.001, verify: { expr: "0.5*2*60", equals: 60 }, explanation: "Q = It = 0.50 A × 120 s = 60 C." },
    { id: "e2", type: "numeric", difficulty: 1, focus: "procedural", unit: "W", prompt: [{ kind: "text", text: "A torch bulb draws 0.30 A from a 9.0 V battery. What is its power?" }], hints: ["P = IV."], answer: 2.7, tolerance: 0.001, verify: { expr: "0.3*9", equals: 2.7 }, explanation: "P = 0.30 A × 9.0 V = 2.7 W." },
    { id: "e3", type: "numeric", difficulty: 2, focus: "procedural", unit: "V", prompt: [{ kind: "text", text: "Resistors of 5.0 Ω, 10 Ω and 15 Ω are in series across 6.0 V. What is the voltage across the 10 Ω resistor?" }], hints: ["Find the current first."], answer: 2, tolerance: 0.001, verify: { expr: "6/(5+10+15)*10", equals: 2 }, explanation: "R = 30 Ω, I = 0.20 A, V = 0.20 × 10 = 2.0 V." },
    { id: "e4", type: "numeric", difficulty: 2, focus: "procedural", unit: "Ω", prompt: [{ kind: "text", text: "Find the combined resistance of 20 Ω and 30 Ω in parallel." }], hints: ["1/R = 1/20 + 1/30."], answer: 12, tolerance: 0.001, verify: { expr: "1/(1/20+1/30)", equals: 12 }, explanation: "1/R = 3/60 + 2/60 = 5/60, R = 12 Ω." },
    { id: "e5", type: "numeric", difficulty: 3, focus: "application", gapSkill: "units_measurement", unit: "Ω", prompt: [{ kind: "text", text: "An LED needs 2.0 V and 20 mA. It is powered from a 5.0 V supply through a series resistor. What resistance is needed?" }], hints: ["The resistor takes the remaining voltage.", "Convert 20 mA to amperes."], answer: 150, tolerance: 0.001, verify: { expr: "(5-2)/0.02", equals: 150 }, explanation: "V_R = 5.0 − 2.0 = 3.0 V; R = 3.0 / 0.020 = 150 Ω." },
    { id: "e6", type: "mcq", difficulty: 2, focus: "conceptual", prompt: [{ kind: "text", text: "Two identical lamps are in parallel on an ideal battery. A third identical lamp is added in parallel. What happens?" }], options: ["The first two lamps get dimmer", "The first two stay equally bright and the battery current increases", "All lamps get brighter", "The battery current decreases"], answer: 1, optionFeedback: ["Each branch still has the full battery voltage.", null, "Each lamp's voltage is unchanged, so its power is unchanged.", "More paths means lower total resistance and more current."], hints: ["What is the voltage across each parallel branch?"], explanation: "Each branch keeps the full voltage, so each lamp's current and power are unchanged; the total current rises by one lamp's current." },
    { id: "e7", type: "numeric", difficulty: 2, focus: "procedural", unit: "W", prompt: [{ kind: "text", text: "A 4.0 Ω resistor carries 3.0 A. At what rate does it transfer energy?" }], hints: ["Use P = I²R."], answer: 36, tolerance: 0.001, verify: { expr: "3^2*4", equals: 36 }, explanation: "P = (3.0)² × 4.0 = 36 W." },
  ],
  application: {
    title: "What does the kettle cost?",
    scenario: [
      { kind: "text", text: "A 2000 W kettle on a 230 V mains supply is used for 6 minutes a day for 30 days. Electricity costs 0.15 per kWh (an illustrative price)." },
    ],
    questions: [
      { id: "ap1", type: "numeric", difficulty: 2, focus: "application", unit: "kWh", prompt: [{ kind: "text", text: "How much energy does the kettle use in 30 days?" }], hints: ["Work in kW and hours.", "6 minutes = 0.1 h."], answer: 6, tolerance: 0.001, verify: { expr: "2*0.1*30", equals: 6 }, explanation: "E = 2.0 kW × 0.10 h × 30 = 6.0 kWh, costing 6.0 × 0.15 = 0.90." },
      { id: "ap2", type: "numeric", difficulty: 2, focus: "application", unit: "A", prompt: [{ kind: "text", text: "What current does the kettle draw? Give 2 significant figures or more." }], hints: ["I = P/V."], answer: 8.6957, tolerance: 0.01, verify: { expr: "2000/230", equals: 8.6957, tolerance: 0.0001 }, explanation: "I = 2000 W / 230 V ≈ 8.7 A." },
      { id: "ap3", type: "mcq", difficulty: 2, focus: "application", prompt: [{ kind: "text", text: "Which fuse rating is most suitable for the kettle's plug?" }], options: ["3 A", "5 A", "13 A", "30 A"], answer: 2, optionFeedback: ["Below the normal 8.7 A, so it would blow in normal use.", "Below the normal current.", null, "Far above the operating current, so it would not protect the cable from a fault."], hints: ["The fuse should be just above the normal current."], explanation: "Choose the smallest standard rating above the operating current of about 8.7 A: 13 A." },
    ],
  },
  assessment: [
    { id: "a1", type: "numeric", difficulty: 1, focus: "procedural", unit: "Ω", prompt: [{ kind: "text", text: "A resistor carries 0.25 A when 12 V is across it. What is its resistance?" }], hints: [], answer: 48, tolerance: 0.001, verify: { expr: "12/0.25", equals: 48 }, explanation: "R = V/I = 12 / 0.25 = 48 Ω." },
    { id: "a2", type: "numeric", difficulty: 2, focus: "procedural", unit: "A", prompt: [{ kind: "text", text: "A 4.0 Ω and a 12 Ω resistor are in parallel across 6.0 V. What total current does the supply provide?" }], hints: [], answer: 2, tolerance: 0.001, verify: { expr: "6/4+6/12", equals: 2 }, explanation: "Branch currents 1.5 A and 0.5 A add to 2.0 A (or R = 3.0 Ω, I = 6.0/3.0)." },
    { id: "a3", type: "mcq", difficulty: 1, focus: "conceptual", prompt: [{ kind: "text", text: "In a series circuit, which quantity is the same for every component?" }], options: ["Potential difference", "Current", "Power", "Resistance"], answer: 1, hints: [], explanation: "There is only one path, so by charge conservation the same current flows through each component." },
    { id: "a4", type: "numeric", difficulty: 3, focus: "procedural", unit: "Ω", prompt: [{ kind: "text", text: "A lamp is rated 60 W at 230 V. What is its operating resistance?" }], hints: [], answer: 881.67, tolerance: 0.01, verify: { expr: "230^2/60", equals: 881.67, tolerance: 0.0001 }, explanation: "R = V²/P = 230² / 60 ≈ 880 Ω (882 Ω to 3 s.f.)." },
    { id: "a5", type: "mcq", difficulty: 2, focus: "application", prompt: [{ kind: "text", text: "Why are household sockets wired in parallel?" }], options: ["So total resistance increases", "So each appliance gets the full mains voltage and can be switched independently", "So the same current flows through every appliance", "So less energy is used"], answer: 1, hints: [], explanation: "Parallel branches each have the supply voltage, and opening one branch does not break the others." },
  ],
  summary: {
    points: [
      "Current is flow of charge (A); potential difference is energy per charge (V); resistance is V/I (Ω).",
      "Series: same current, voltages add, resistances add.",
      "Parallel: same voltage, currents add, total resistance is less than the smallest branch.",
      "Power P = IV; energy E = Pt; 1 kWh = 3.6 MJ.",
    ],
    formulas: ["I = Q/t", "V = IR", "R_s = R₁ + R₂", "1/R_p = 1/R₁ + 1/R₂", "P = IV = I²R = V²/R", "E = Pt"],
  },
};
